language: node_js
node_js:
  - "9.11.2"

install:
  - npm i

script:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master